[General]
bypass-system = true 
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com, *.ru
bypass-tun = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32
dns-server = system, 1.1.1.1, 8.8.8.8
update-url = https://raw.githubusercontent.com/imartmax/shadowrocket-configuration-file/main/iOS.conf interval=60 strict=true

[Rule]
# Telegram 
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Telegram/Telegram.list,PROXY

# WhatsApp
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/WhatsApp/WhatsApp.list,PROXY

# Signal
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Signal/Signal.list,PROXY

# Anthropic
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Anthropic/Anthropic.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Claude/Claude.list,PROXY

# Gemini
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Gemini/Gemini.list,PROXY

# Google
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Google/Google.list,PROXY

# Meta
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Instagram/Instagram.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Facebook/Facebook.list,PROXY

# OpenAI
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/OpenAI/OpenAI.list,PROXY

# YouTube
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/YouTube/YouTube.list,PROXY


DOMAIN-SUFFIX,telesco.pe,Proxy
DOMAIN-SUFFIX,nicegram.app,Proxy
DOMAIN-SUFFIX,telegramdownload.com,Proxy
DOMAIN-SUFFIX,cdn-telegram.org,Proxy
DOMAIN-SUFFIX,comments.app,Proxy
DOMAIN-SUFFIX,contest.com,Proxy
DOMAIN-SUFFIX,fragment.com,Proxy
DOMAIN-SUFFIX,graph.org,Proxy
DOMAIN-SUFFIX,quiz.directory,Proxy
DOMAIN-SUFFIX,signal.org,Proxy
DOMAIN-SUFFIX,tdesktop.com,Proxy
DOMAIN-SUFFIX,telega.one,Proxy
DOMAIN-SUFFIX,telegram-cdn.org,Proxy
DOMAIN-SUFFIX,usercontent.dev,Proxy
DOMAIN-SUFFIX,tgram.org,Proxy
DOMAIN-SUFFIX,torg.org,Proxy
DOMAIN-SUFFIX,t.co,Proxy
DOMAIN-SUFFIX,telegram.org.cdn.cloudflare.net,Proxy  
DOMAIN-SUFFIX,threads.net,Proxy
DOMAIN-SUFFIX,tumblr.com,Proxy
DOMAIN-SUFFIX,twimg.com,Proxy
DOMAIN-SUFFIX,twitter.co,Proxy
DOMAIN-SUFFIX,twitter.com,Proxy
DOMAIN-SUFFIX,twitthat.com,Proxy
DOMAIN-SUFFIX,twtkr.com,Proxy
DOMAIN-SUFFIX,twttr.com,Proxy
DOMAIN-SUFFIX,youtu.be,Proxy
DOMAIN-SUFFIX,youtube.com,Proxy
DOMAIN-SUFFIX,youtubei.googleapis.com,Proxy
DOMAIN-SUFFIX,vimeo.com,Proxy
DOMAIN-SUFFIX,vimeocdn.com,Proxy
DOMAIN-SUFFIX,wa.me,Proxy
DOMAIN-SUFFIX,whatsapp.com,Proxy
DOMAIN-SUFFIX,whatsapp.net,Proxy
DOMAIN-SUFFIX,whatsapp-calls.net,Proxy
DOMAIN-SUFFIX,x.ai,Proxy
DOMAIN-SUFFIX,x.com,Proxy

DOMAIN-SUFFIX,ru-board.com,Proxy
DOMAIN-SUFFIX,rutracker.org,Proxy
DOMAIN-SUFFIX,iherb.com,Proxy
DOMAIN-SUFFIX,dyson.com,Proxy
DOMAIN-SUFFIX,canva.com,Proxy

DOMAIN-SUFFIX,flibusta.is,Proxy
DOMAIN-SUFFIX,x.ai,Proxy
DOMAIN-SUFFIX,x.com,Proxy
  
# Финальное правило
FINAL,DIRECT
