[Rule]
# Telegram 
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Telegram/Telegram.list,PROXY

# WhatsApp
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/WhatsApp/WhatsApp.list,PROXY

# Signal
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Signal/Signal.list,PROXY

# Anthropic
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Anthropic/Anthropic.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Claude/Claude.list,PROXY

# Gemini
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Gemini/Gemini.list,PROXY

# Google
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Google/Google.list,PROXY

# Meta
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Instagram/Instagram.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Facebook/Facebook.list,PROXY

# OpenAI
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/OpenAI/OpenAI.list,PROXY

# YouTube
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/YouTube/YouTube.list,PROXY

# ALL
RULE-SET,https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Russia/inside-clashx.lst,PROXY

# Yandex,Mail,VK - direct
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Yandex/Yandex.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Mailru/Mailru.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/VK/VK.list,DIRECT

# Россия — direct
RULE-SET,https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Russia/outside-clashx.lst,DIRECT
GEOIP,RU,DIRECT

DOMAIN-SUFFIX,kant.ru,Proxy
DOMAIN-SUFFIX,skladchina.biz,Proxy

# AlfaBank
DOMAIN-SUFFIX,alfabank.com,DIRECT
DOMAIN-SUFFIX,alfabank.ru,DIRECT
PROCESS-NAME,AlfaBank,DIRECT

DOMAIN-SUFFIX,.ru,DIRECT
DOMAIN-SUFFIX,.com.ru,DIRECT
DOMAIN-SUFFIX,.exnet.su,DIRECT
DOMAIN-SUFFIX,.ru.net,DIRECT 
DOMAIN-SUFFIX,.pp.ru,DIRECT
DOMAIN-SUFFIX,.net.ru,DIRECT
DOMAIN-SUFFIX,.org.ru,DIRECT

# Финальное правило
FINAL,DIRECT
